#pragma once

#define PT_LANG_UNKNOWN                         "desconhecido"

#define PT_LANG_BOOLEAN                         "booleano"
#define PT_LANG_BIT8                            "bit8"
#define PT_LANG_INTEGER8                        "inteiro8"
#define PT_LANG_BIT16                           "bit16"
#define PT_LANG_INTEGER16                       "inteiro16"
#define PT_LANG_BIT32                           "bit32"
#define PT_LANG_INTEGER32                       "inteiro32"
#define PT_LANG_BIT64                           "bit64"
#define PT_LANG_INTEGER64                       "inteiro64"
#define PT_LANG_FLOAT32                         "real32"
#define PT_LANG_FLOAT64                         "real64"
#define PT_LANG_TEXT                            "texto"
#define PT_LANG_FUNCTION                        "funcao"
#define PT_LANG_POINTER                         "ponteiro"

#define PT_LANG_TRUE                            "verdadeiro"
#define PT_LANG_FALSE                           "falso"

#define PT_LANG_CAST                            "converter"
#define PT_LANG_SIZEOF                          "tamanho"
#define PT_LANG_TYPE                            "tipo"

#define PT_LANG_ASSIGN                          "<-"
#define PT_LANG_ADD                             "+"
#define PT_LANG_SUBTRACT                        "-"
#define PT_LANG_MULTIPLY                        "*"
#define PT_LANG_DIVIDE                          "/"
#define PT_LANG_REMAINDER                       "%%"
#define PT_LANG_NEGATIVE                        "'"
#define PT_LANG_POWER                           "\\"
#define PT_LANG_EQUAL                           "=="
#define PT_LANG_INEQUAL                         "<>"
#define PT_LANG_GREATER                         ">"
#define PT_LANG_GREATER_OR_EQUAL                ">="
#define PT_LANG_LESSER                          "<"
#define PT_LANG_LESSER_OR_EQUAL                 "<="
#define PT_LANG_AND                             "&&"
#define PT_LANG_OR                              "||"
#define PT_LANG_XOR                             "^^"
#define PT_LANG_NEGATE                          "!"
#define PT_LANG_BIT_AND                         "&"
#define PT_LANG_BIT_OR                          "|"
#define PT_LANG_BIT_XOR                         "^"
#define PT_LANG_BIT_NEGATE                      "~"
#define PT_LANG_LEFT_SHIFT                      "<<"
#define PT_LANG_RIGHT_SHIFT                     ">>"
